name: alphafold_venv
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - conda-forge::cudatoolkit==11.1.*
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pip:
      - biopython==1.79
      - deepspeed==0.5.10
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.2
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==3.10.0.2
      - wandb==0.12.21
      - git+https://github.com/NVIDIA/dllogger.git
      - absl-py==1.0.0
      - chex==0.0.7
      - dm-haiku==0.0.7
      - dm-tree==0.1.6
      - pandas==1.3.4
      - protobuf==3.20.1
      - tensorflow-cpu==2.9.0
      - docker==5.0.0
